### ISSUE TITLE
issue with vignettes - Part two missing and part 1 replicated

### ISSUE THREAD

**Issue by Phytopath85** [dbailleul/RClone#2]
Hi, 

I have no idea how to use GitHub or if this 'issues' section is even the correct place to contact contributors! Sorry if it's miss-placed!
The link to the second vignette on the Code tab above only recreates a copy of the first vignette . The same thing happens when you type the following commands into the R console, launching a copy of the first vignette (analysis of a single population)

>install.packages("RClone")
>vignette("RClone_qmsevpops") #analysing several populations

I'd really like to read the second vignette!

Thanks

**Comment by dbailleul** [comment]
Dear PhytoPath85,

I'm sorry for the answer delay.
I don't remember having an email warning me of your question.

You are in the good place to ask this kind of question.
Do not hesitate to contact me directly by email if I'm too long to answer.

As for your question, really ... I don't know.
It's working with my RClone version.

Be sure to use the RClone version from Github (see the home page, the commands are written).

I'm putting there the generated vignette. 

I hope it's not too late.

Sincerely,

Diane
[RClone_qmsevpops.pdf](https://github.com/dbailleul/RClone/files/4947653/RClone_qmsevpops.pdf)
